name: environment
channels:
  - conda-forge
dependencies:
  - cartopy
  - cmocean
  - cython
  - gdal
  - matplotlib
  - netcdf4
  - netcdftime
  - numpy
  - pandas
  - pillow
  - pyproj
  - pyyaml
  - scipy
  - shapely
